name: CD - Build, Push Image, (Optional) Rollout

on:
  push:
    branches: [ master ]

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/intens-api-2022
  TAG: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # potrebno za push na GHCR
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 8 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'

      - name: Build JAR
        run: mvn -B -e -DskipTests clean package

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push Docker image (Dockerfile.ci)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.ci
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ env.TAG }}

  trigger-render:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: ${{ secrets.RENDER_DEPLOY_HOOK != '' }}
    steps:
      - name: Trigger Render deploy
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
